# Generated by Django 5.1.2 on 2024-10-29 05:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=tinymce.models.HTMLField(default='Content not available'),
        ),
    ]
